controller_list:
  - name: "robot_rail_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: ["linear_actuator_carriage_joint",
            "robot_elbow_joint",
            "robot_shoulder_lift_joint",
            "robot_shoulder_pan_joint",
            "robot_wrist_1_joint",
            "robot_wrist_2_joint",
            "robot_wrist_3_joint"]
