robot_rail_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - linear_actuator_carriage_joint
     - robot_elbow_joint
     - robot_shoulder_lift_joint
     - robot_shoulder_pan_joint
     - robot_wrist_1_joint
     - robot_wrist_2_joint
     - robot_wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.2
      linear_actuator_carriage_joint: {trajectory: 0.05, goal: 0.05}
      robot_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      robot_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      robot_elbow_joint: {trajectory: 0.1, goal: 0.1}
      robot_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      robot_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      robot_wrist_3_joint: {trajectory: 0.15, goal: 0.15}
  gains:
      linear_arm_actuator_joint: {p: 10000, d: 500, i: 0, i_clamp: 1}
      robot_shoulder_pan_joint: {p: 10000, d: 150, i: 0, i_clamp: 1}
      robot_shoulder_lift_joint: {p: 50000, d: 150, i: 10, i_clamp: 50}
      robot_elbow_joint: {p: 50000, d: 150, i: 1, i_clamp: 25}
      robot_wrist_1_joint: {p: 100, d: 5, i: 0, i_clamp: 1}
      robot_wrist_2_joint: {p: 75, d: 2, i: 0, i_clamp: 1}
      robot_wrist_3_joint: {p: 25, d: 1, i: 0, i_clamp: 1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
